---
# tasks file for desktop
- name: Install git
  win_chocolatey:
    name: git
    state: present

- name: Install notepadplusplus version 7.5.6
  win_chocolatey:
    name: notepadplusplus.install
    version: '7.5.6'

- name: Upgrade installed packages
  win_chocolatey:
    name: all
    state: latest
